name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: K3S with Calico and Helm
        uses: manics/action-k3s-helm@v0.2.1
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
      - name: Install Tools
        run: make tools-install
      - name: Read configuration
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://volt.cap.explore.suse.dev/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/carrier "docker_registry_username"     | REGISTRY_USERNAME;
            secret/data/carrier "docker_registry_password"     | REGISTRY_PASSWORD;
      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH
      - name: Install Carrier
        run: |
          ./carrier install
      - name: Push an App
        run: |
          git config --global user.email "ci@suse.dev"
          git config --global user.name "cibot"
          ./carrier push "ci${GITHUB_RUN_NUMBER}" ./sample-app
      - name: Test App
        run: |
          external_ip=$(kubectl get svc -A --field-selector='metadata.name=traefik' -o json | jq -r .items[0].status.loadBalancer.ingress[0].ip)
          curl --fail http://"ci${GITHUB_RUN_NUMBER}.${external_ip}.nip.io"
      - name: Uninstall Carrier
        run: |
          ./carrier uninstall
      - name: Log
        if: ${{ always() }}
        run: |
          cat "$HOME/.carrier.log"
          kubectl get all -A -o wide
